from models.cnn import DefaultCNNFeatureExtractor
from models.mlp import CuriosityLinearInverseModule
from models.mlp import CuriosityLinearFeaturePredictor
from models.rnn import DefaultLSTMInnerStatePredictor
from models.actor_critic import DefaultDiscreteLinearActorCritic, LSTMDiscreteLinearActorCritic