from models.feature_extractor import DefaultCNNFeatureExtractor

from models.inverse_module import CuriosityLinearInverseModule

from models.feature_predictor import CuriosityLinearFeaturePredictor

from models.inner_state_predictor import DefaultLSTMInnerStatePredictor

from models.controller import DefaultDiscreteLinearActorCritic, LSTMDiscreteLinearActorCritic